services:
  twitter-image-collage-maker:
    image: ghcr.io/thelovinator1/twitter-image-collage-maker:master
    env_file:
      - .env
    container_name: twitter-image-collage-maker
    environment:
      - WEBHOOK_URL=${WEBHOOK_URL}
      - URL=${URL}
      - STATIC_LOCATION=${STATIC_LOCATION}
      - DISCORD_ID=${DISCORD_ID}
      - BEARER_TOKEN=${BEARER_TOKEN}
    ports:
      - "5000:5000"
    volumes:
      - tweet_images:/usr/share/twitter-image-collage-maker/
    restart: unless-stopped
volumes:
  tweet_images: